name: 'Experimental Forms Generator'
description: 'This automatically generates the CCS Stuttgart experimental consent & experiment forms'

inputs:
  language:
    description: 'language en or de'
    default: 'en'
    required: true
  token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
runs:
  using: "composite"
  steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ inputs.token }}
        with:
          tinytex: true
          version: 1.5.45
          
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'

      - name: Cache R packages 
       
        uses: actions/cache@v4
        with: 
           path: ${{ env.R_LIBS_USER }} 
           key: r-localv1
      - name: install dependencies
        shell: bash
        run: |
          R -e 'install.packages(c("rmarkdown","RcppTOML"))'
  
      - name: Download project TOML file
        uses: actions/download-artifact@v4
        with:
          name: _callerproject.toml
      - name: Render form
        uses: quarto-dev/quarto-actions/render@v2
        env: 
          QUARTO_PROFILE: ${{ inputs.language }}
        with:
          to: custom-typst
          path: ${{github.action_path}}
      - name: Upload consent form
        uses: actions/upload-artifact@v4
        with:
          name: consent_${{ inputs.language }}
          path: ${{github.action_path}}/consent.pdf
      - name: Upload data privacy form
        uses: actions/upload-artifact@v4
        with:
          name: data_privacy_${{ inputs.language }}
          path: ${{github.action_path}}/data_privacy.pdf
          
