name: 'Experimental Forms Generator'
description: 'This automatically generates the CCS Stuttgart experimental consent & experiment forms'

inputs:
  language:
    description: 'language en or de'
    default: 'en'
    required: true
  token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
  
  project_toml:
     required: true
     type: string
runs:
  using: "composite"
  steps:
   
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Save project TOML content to file
        shell: bash
        run: |
          # Write the input content to _project.toml
          echo "${{ inputs.project_toml }}"  | base64 --decode > _project.toml
      - name: Verify file content
        shell: bash
        run: |
          cat _project.toml

          
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'

      - name: Cache R packages 
        uses: actions/cache@v4
        with: 
           path: ${{ env.R_LIBS_USER }} 
           key: r-localv1
      - name: install dependencies
        shell: bash
        run: |
          R -e 'install.packages(c("rmarkdown","RcppTOML"))'

      - name: Validate/Debug R-TOML
        shell: bash
        run: |
          # Example R script call using the absolute path
          Rscript -e '
            toml_file <- "_project.toml"
            if (file.exists(toml_file)) {
              library(RcppTOML)
              toml_content <- parseTOML(toml_file)
              print(toml_content)
            } else {
              stop("File not found: ", toml_file)
            }
          '
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ inputs.token }}
        with:
          tinytex: true
          version: 1.5.45

      - name: 'Render manually'
        env:
         QUARTO_PRINT_STACK: true
        run: |
          quarto render ${{ github.action_path }} --to custom-typst
        shell: bash
        env: 
          QUARTO_PROFILE: ${{ inputs.language }}
      - name: Upload consent form
        uses: actions/upload-artifact@v4
        with:
          name: consent_${{ inputs.language }}
          path: ${{github.action_path}}/consent.pdf
      - name: Upload data privacy form
        uses: actions/upload-artifact@v4
        with:
          name: data_privacy_${{ inputs.language }}
          path: ${{github.action_path}}/data_privacy.pdf
          
