name: 'Experimental Forms Generator'
description: 'This automatically generates the CCS Stuttgart experimental consent & experiment forms'

inputs:
  language:
    description: 'language en or de'
    default: 'en'
    required: true
  token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
  
  project_toml:
     required: true
     type: string
runs:
  using: "composite"
  steps:
   
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Save project TOML content to file
        shell: bash
        run: |
          # Write the input content to _project.toml
          echo "${{ inputs.project_toml }}"  | base64 --decode > _project.toml
      - name: Verify file content
        shell: bash
        run: |
          cat _project.toml

          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        shell: bash
        run: |
          pip install tomli

      - name: Validate/Debug TOML
        shell: bash
        run: |
          python3 << 'EOF'
          import tomli
          import os
          toml_file = "_project.toml"
          if os.path.exists(toml_file):
              with open(toml_file, "rb") as f:
                  toml_content = tomli.load(f)
                  print(toml_content)
          else:
              raise FileNotFoundError(f"File not found: {toml_file}")
          EOF
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ inputs.token }}
        with:
          tinytex: true
          version: 1.5.45

      - name: 'Render manually'
        env:
         QUARTO_PRINT_STACK: true
         QUARTO_PROFILE: ${{ inputs.language }}
        run: |
          quarto render ${{ github.action_path }} --to custom-typst
        shell: bash
        
      - name: Upload consent form
        uses: actions/upload-artifact@v4
        with:
          name: consent_${{ inputs.language }}
          path: ${{github.action_path}}/consent.pdf
      - name: Upload data privacy form
        uses: actions/upload-artifact@v4
        with:
          name: data_privacy_${{ inputs.language }}
          path: ${{github.action_path}}/data_privacy.pdf
          
