---
format:
    custom-typst:
        paper: a4
execute:
    echo: false

---

```{r,setup}
library(RcppTOML)
files = Sys.glob(file.path(getwd(), '*toml'))
toml = parseTOML(files[1])

```

:::: {.block fill="none" inset="0pt" radius="4pt" width="60%"}
::: {.content-visible when-profile="de"}
Verantwortlicher Wissenschaftler: Benedikt Ehinger
:::
::: {.content-visible when-profile="en"}
Responsible Principal Investigator: Benedikt Ehinger
:::
Institut für Visualisierung und Interaktive Systeme (VIS) 
\
University of Stuttgart
\
Universitätstraße 34
\
70569 Stuttgart
\
E-mail: benedikt.ehinger@vis.uni-stuttgart.de
::::

\
 
:::: {.content-visible when-profile="de"}
# Aufklärung / Einwilligung
::::
::: {.content-visible when-profile="en"}
# Informed consent
:::

\

::: {.content-visible when-profile="de"}
Sehr geehrte Teilnehmerin, sehr geehrter Teilnehmer,   
Sie haben sich freiwillig zur Teilnahme an dieser Studie gemeldet. Hier erhalten Sie nun einige Informationen zu Ihren Rechten und zum Ablauf des folgenden Experiments. Bitte lesen Sie sich die folgenden Abschnitte sorgfältig durch.
:::
::: {.content-visible when-profile="en"}
Dear participant,
You have volunteered to participate in this study. Here you will now receive some information about your rights and the procedure of the following experiment. Please read the following sections carefully. 
:::

::: {.content-visible when-profile="de"}
## 1) **Ziel der Studie**

In dieser Studie untersuchen wir, wie Menschen Bilder wahrnehmen, indem wir die Gehirnaktivität mit EEG und die Augenbewegungen mit einem Eye-Tracker aufzeichnen.
:::
::: {.content-visible when-profile="en"}
## 1) **Purpose of the study**

In this study, we will investigate how humans perceive images by recording brain activity with EEG and eye movements using an eye-tracker.
:::


::: {.content-visible when-profile="de"}
## 2) **Ablauf der Studie**

Die Studie läuft wie folgt ab:
:::
::: {.content-visible when-profile="en"}
## 2) **Study procedure**

The study will proceed as follows:
:::

::: {.content-visible when-profile="de"}
1. Wir führen einen Sehtest durch (Sehschärfe und dominantes Auge). 
:::
::: {.content-visible when-profile="en"}
1. We perform an eye test (visual acuity and dominant eye). 
:::

::: {.content-visible when-profile="de"}
1. Wir fragen mündlich ab, ob eine photosensitive Epilepsie, photosensitive Migräne oder eine andere neurologische oder psychiatrische Erkrankung (schwere Depression, ADHS, Autismus o.ä.) vorliegt.
:::
::: {.content-visible when-profile="en"}
1. We verbally query whether there is photosensitive epilepsy, photosensitive migraine or any other neurological disorder (major depression, ADHD, autism, or similar).
:::


`r if (toml$Consentform$use_eeg!=TRUE) ":::: {.content-hidden}"`
::: {.content-visible when-profile="de"}
1. EEG: Sie ziehen eine EEG-Kappe an. Mit einer stumpfen Nadel wird ein Elektrodengel (ähnlich wie bei Ultraschall) aufgetragen und die oberste Schicht der Kopfhaut sanft aufgeraut, um eine ideale Leitfähigkeit herzustellen.
:::
::: {.content-visible when-profile="en"}
1. EEG: You put on an EEG cap. An electrode gel (similar to ultrasound) is applied with a blunt needle and the top layer of the scalp is gently roughened to create ideal conductivity.
:::
`r if (toml$Consentform$use_eeg!=TRUE) "::::"`



`r if (toml$Consentform$use_eyetracking!=TRUE) ":::: {.content-hidden}"`
::: {.content-visible when-profile="de"}
1. Eye-Tracking: Der Eye-Tracker muss kalibriert werden, dazu wird ein sich bewegender Punkt auf dem Bildschirm angezeigt, dem Sie mit ihrem Blick folgen.
:::
::: {.content-visible when-profile="en"}
1. Eye-tracking: The eye tracker needs to be calibrated, for this, a moving dot will appear on the monitor which you will follow with your gaze.
:::
`r if (toml$Consentform$use_eyetracking!=TRUE) "::::"`



::: {.content-visible when-profile="de"}
1. Es werden Ihnen verschiedene Bilder auf dem Monitor präsentiert. Ihre Aufgabe ist es, die Bilder frei zu erkunden.
:::
::: {.content-visible when-profile="en"}
1. We will present different pictures on the screen. Your task is to freely explore these pictures.
:::



`r if (toml$Consentform$use_eeg!=TRUE) ":::: {.content-hidden}"`
::: {.content-visible when-profile="de"}
1. Die EEG-Kappe wird abgenommen und Sie können sich das Gel aus den Haaren waschen.
:::
::: {.content-visible when-profile="en"}
1. The EEG cap will be removed and you can wash the gel out of your hair.
:::
`r if (toml$Consentform$use_eeg!=TRUE) "::::"`



::: {.content-visible when-profile="de"}
Inklusive der Fragebögen und Vorbereitungen, dauert der Versuch ca. 3 Stunden.
:::
::: {.content-visible when-profile="en"}
Including the questionnaires and preparations, the experiment takes about 3 hours.
:::


::: {.content-visible when-profile="de"}
## 3) **Risiken und Nebenwirkungen**

Diese Studie ist nach derzeitigem Wissensstand ungefährlich und für die Teilnehmenden schmerzfrei. Durch Ihre Teilnahme an dieser Studie setzen Sie sich keinen besonderen Risiken aus und es sind keine Nebenwirkungen bekannt. Da diese Studie in Ihrer Gesamtheit neu ist, kann das Auftreten von noch unbekannten Nebenwirkungen allerdings nicht ausgeschlossen werden.

**Wichtig:** Teilen Sie dem Versuchsleiter bitte umgehend mit, falls Sie an einer neurologischen Krankheit erkrankt sind, starke (Licht-)Stimulation Migräne auslösen kann, oder Sie einen epileptischen Anfall hatten. Bei Fragen hierzu wenden Sie sich bitte an die Versuchsleitung.
:::
::: {.content-visible when-profile="en"}
## 3) **Risks and side effects**

According to current knowledge, this study is harmless and painless for the participants. By participating in this study, you are not exposing yourself to any particular risks and there are no known side effects. In the case of virtual reality experiments, exposure may cause motion sickness or eye strain. However, because this study is new in its entirety, the occurrence of as-yet-unknown side effects cannot be completely ruled out. 

**Important:** Please inform the experimenter immediately if you have a neurological disease, if strong (light) stimulation can trigger migraine, or if you have had an epileptic seizure. If you have any questions about this, please contact the experimental investigator.
:::


::: {.content-visible when-profile="de"}
## 4) **Abbruch der Studie**

Die Teilnahme an der Studie ist freiwillig. Sie können jederzeit und ohne Angabe von Gründen Ihre Einwilligung zur Teilnahme an dieser Studie widerrufen, ohne dass Ihnen daraus Nachteile entstehen. Auch wenn Sie die Studie vorzeitig abbrechen, haben Sie dennoch Anspruch auf eine entsprechende Vergütung für den bis dahin erbrachten Zeitaufwand.

Sollten Sie während des Experiments Kopfschmerzen oder Unwohlsein anderer Art verspüren, dann informieren Sie bitte umgehend die Versuchsleitung.
:::
::: {.content-visible when-profile="en"}
## 4) **Termination of the experiment**

Participation in the study is voluntary. You may withdraw your consent to participate in this study at any time without giving any reason and without any disadvantages. Even if you terminate the study prematurely you will be remunerated accordingly for the time spent up to that point.

If you experience headaches or any other kind of discomfort during the experiment, please inform the experimental investigator immediately.
:::


::: {.content-visible when-profile="de"}
## 5) **Vertraulichkeit**

Ihre Daten werden nur in pseudonymisierter Form (z. B. „versuchsperson-003“) gespeichert. Die Zuordnungsdatei wird nach Abschluss der Datenerhebung gelöscht. Die Daten werden für wissenschaftliche Publikationen, aber auch als offene wissenschaftlichen Daten für Dritte zugänglich gemacht. Eine Löschung ist dann nicht mehr möglich. Der Datenschutz ist in der Datenschutzerklärung näher geregelt.
:::
::: {.content-visible when-profile="en"}
## 5) **Confidentiality**

Your data will only be stored in pseudonymized form (e.g. "sub-003"). The mapping file will be deleted after the completion of the data collection. The data will be made available for scientific publications, but also as open scientific data for third parties. Deletion is then no longer possible. Data protection is regulated in more detail in the data privacy policy.
:::


::: {.content-visible when-profile="de"}
## 6) **Vergütung** 

Die Studie wird mit `r toml$Consentform$pay_per_hour` € pro Stunde vergütet. Angefangene halbe Stunden werden aufgerundet.
:::
::: {.content-visible when-profile="en"}
## 6) **Remuneration**

The study will be remunerated with `r toml$Consentform$pay_per_hour` € per hour. Partial half hours will be rounded up. 
:::


::: {.content-visible when-profile="de"}
## 7) **Einverständniserklärung** 

Hiermit versichere ich, dass ich die oben beschriebenen Teilnahmeinformationen verstanden habe und mit den genannten Teilnahmebedingungen einverstanden bin, insbesondere mit:

*- einer unbegrenzten Speicherung meiner pseudonymisierten Daten.*

*- einer Nutzung meiner pseudonymisierten Daten für das aktuelle Forschungsprojekt und für weitere ausschließlich wissenschaftliche Zwecke.*

*- einer Veröffentlichung meiner pseudonymisierten Daten als offene Daten.*

\
\
\

.........................................................................

Ort, Datum, Unterschrift
:::
::: {.content-visible when-profile="en"}
## 7) **Declaration of consent**

I hereby confirm that I have understood the participant information described above and that I agree to the stated conditions of participation, in particular:

*- an unlimited storage of my pseudonymized data.*

*- the usage of my pseudonymized data for the current research project and for other exclusively scientific purposes.*

*- a publication of my pseudonymized data as open data.*
 
\
\
\

.........................................................................

Place, Date, Signature
:::
