---
format:
    custom-typst:
        paper: a4
        keep-typ: false
execute:
    echo: false

---

```{python,setup}
import tomli
with open("_project.toml", "rb") as f:
    toml = tomli.load(f)
```

:::: {.block fill="none" inset="0pt" radius="4pt" width="60%"}
::: {.content-visible when-profile="de"}
`{python} toml['Consentform']['researcher_details_de']`
:::
::: {.content-visible when-profile="en"}
`{python} toml['Consentform']['researcher_details_en']`
:::
::::

\
 
:::: {.content-visible when-profile="de"}
# Datenschutzerklärung ^[Basierend auf der standardisierten open-brain consent-form v1.0.1] 
::::
::: {.content-visible when-profile="en"}
# Data Privacy Policy ^[Based on the standardized open-brain consent-form v1.0.1]
:::

\

::: {.content-visible when-profile="de"}
Sehr geehrte Teilnehmerin, sehr geehrter Teilnehmer,   

Sie haben sich freiwillig zur Teilnahme an dieser Studie gemeldet. Hier erhalten Sie nun einige Informationen zum Datenschutz der erhobenen Daten. Bitte lesen Sie sich die folgenden Abschnitte sorgfältig durch.
:::
::: {.content-visible when-profile="en"}
Dear participant,  

You have volunteered to participate in this study. Here you will now receive some information about the data privacy regulations for the collected data. Please read the following sections carefully. 
:::

::: {.content-visible when-profile="de"}
## 1) **Verwendung und Speicherung Ihrer Daten**

Während die Erhebung, Nutzung und Speicherung Ihrer Daten zum Zwecke der Durchführung der Studie erfolgt, an der Sie derzeit teilnehmen, können diese Daten auch für andere zukünftige Forschungsprojekte im Bereich der Mensch-Computer-Interaktion, der Visualisierung, der klinischen oder kognitiven Neurowissenschaften verwendet werden.  Dazu gehören Daten von Ihrem Gehirn und es können auch Testergebnisse der Studie, an der Sie teilnehmen sowie Daten wie Geschlecht und Alter dazugehören.

Wenn Sie sich zur Teilnahme bereit erklären, machen Sie ein kostenloses und großzügiges Geschenk an die Forschung, die anderen helfen könnte. Es ist möglich, dass ein Teil der Forschung, die mit Ihren Daten durchgeführt wird, schließlich zur Entwicklung neuer Methoden zur Untersuchung des Gehirns, neuer diagnostischer Tests, neuer Medikamente oder anderer kommerzieller Produkte führen könnte. Sollte dies der Fall sein, ist nicht geplant, Ihnen einen Teil der mit solchen Produkten erzielten Gewinne zu überlassen, und Sie haben keine Eigentumsrechte an den Produkten. Wir bitten Sie um Ihre Zustimmung zu diesem Zugriff auf Ihre Daten.
:::
::: {.content-visible when-profile="en"}
## 1) **Usage and storage of your data**

While the collection, use and storage of your data are done for the purpose of conducting the study in which you are currently participating, these data might also be used for other future research projects in the field of human-computer interaction, visualisation, clinical or cognitive neuroscience. This includes data from your brain and/or other behavioural measures, and may also include test results from the study you took part in, and also data such as gender and age.

By agreeing to participate, you will be making a free and generous gift for research that might help others. It is possible that some of the research conducted with your data could eventually lead to the development of new methods of studying the brain, new diagnostic tests, new drugs or other commercial products. Should this be the case, there are no plans to share any of the profits made from such products with you and you will have no ownership rights in the products. We ask for your consent to this access to your data.
:::


::: {.content-visible when-profile="de"}
## 2) **Vertraulichkeit Ihrer Daten**
Nach unserem besten Wissen enthalten die von uns veröffentlichten Daten keine Informationen, die Sie direkt identifizieren können. Um Ihre Privatsphäre zu schützen, werden die Daten mit einem Code versehen, so dass niemand Ihren Namen oder Ihre biografischen Daten kennt. Ihr Name, aber auch andere Informationen, mit denen Sie direkt identifiziert werden können, werden weggelassen. Die Daten können nur anhand von Informationen, die nur den datenverarbeitenden Personen (d.h. den an der Studie beteiligten Personen) zur Verfügung stehen, zu Ihnen zurückverfolgt werden. Diese Informationen bleiben sicher in der örtlichen Forschungseinrichtung gespeichert. Die Daten können in Berichten und Publikationen über die Studie nicht zu Ihnen zurückverfolgt werden. Durch die Verwendung zusätzlicher Daten, die mit Ihrem Namen verknüpft sind (z.B. EEG-Messungen aus ihrer Krankenakte), könnte man jedoch möglicherweise Informationen in unserer Datenbank mit Ihnen in Verbindung bringen.
:::
::: {.content-visible when-profile="en"}
## 2) **Confidentiality of your data**

To the best of our knowledge, the data we release will not contain information that can directly identify you using reasonable means. To protect your privacy, the data will be given a code, so people will not know your name or which data are yours. Your name, but also other information that can directly identify you, will be omitted. Data can only be traced back to you using information only available to the data processor (i.e. people involved in the study). This information will remain safely stored in the local research institute. The data cannot be traced back to you in reports and publications about the study. However, by using additional data linked to your name (for example EEG recordings obtained from your medical records) one could potentially associate your imaging or other information in our database back to you.
:::

::: {.content-visible when-profile="de"}
## 3) **Zugang zu Ihren Daten zur Überprüfung**

Einige Personen können am Forschungsstandort auf alle Ihre Daten zugreifen, auch auf die Originaldaten mit Ihrem Namen. Dies ist notwendig, um zu überprüfen, ob die Studie gut und zuverlässig durchgeführt wird und um Sie und Ihren Arzt oder Ihre Ärztin im Falle von zufälligen Befunden, die sich aus Ihren Messungen ergeben, benachrichtigen zu können. Personen, die zur Überprüfung Zugang zu Ihren Daten haben, sind: das lokale Komitee, das die Sicherheit der Studie überwacht, der Data Controller an der Universität Stuttgart (Datenschutzbeauftragter Herr Schullerer), der für den Hauptprüfer der Studie arbeitet, sowie lokale, nationale und internationale Aufsichtsbehörden. Sie werden Ihre Daten vertraulich behandeln.
:::
::: {.content-visible when-profile="en"}
## 3) **Access to your data for verification**

Some people can access all your data at the research location, including the original data with your name. This is necessary to check whether the study is being conducted properly and reliably and to be able to notify you and your doctor in the event of incidental findings resulting from your measurements. Persons who have access to your data for review are: the local committee that monitors the safety of the study, the data controller at the University of Stuttgart (Datenschutzbeauftragter Herr Schullerer) working for the primary investigator of the study, and local, national and international supervisory authorities. They will keep your data confidential.
:::


::: {.content-visible when-profile="de"}
## 4) **Aufbewahrungsdauer Ihrer Daten**

Es ist nicht geplant, Ihre Daten zu löschen, da sie für legitime Forschungsinteressen wiederverwendet werden können. 
:::
::: {.content-visible when-profile="en"}
## 4) **Retention period of your data**

There is no plan to delete your data as they can be re-used for legitimate research interests.
:::


::: {.content-visible when-profile="de"}
## 5) **Rücknahme der Zustimmung**

Sie können Ihre Zustimmung zur Verwendung Ihrer persönlichen Daten jederzeit widerrufen. Dies gilt sowohl für diese Studie als auch für die Weitergabe für zukünftige Forschungsprojekte. Sie müssen jedoch verstehen, dass es – aufgrund der Anonymisierung – nach der Weitergabe an andere Institutionen unmöglich ist, Ihre Daten aus solchen Kopien zu entfernen.
:::
::: {.content-visible when-profile="en"}
## 5) **Withdrawing consent**

You can withdraw your consent to the use of your personal data at any time. This applies to this study and also to the sharing for future research. You have however to understand that – due to data anonymization – once shared with other institutions, it is impossible to remove your data from such copies.
:::


::: {.content-visible when-profile="de"}
## 6) **Weitergabe an Länder außerhalb der Europäischen Union (EU)** 

Ihre verschlüsselten Daten können auch von Ländern außerhalb der EU abgerufen und an diese gesendet werden. Dies ist notwendig, damit Wissenschaftler mit Sitz außerhalb der EU Analysen durchführen können, um die wissenschaftlichen Ergebnisse dieser Studie zu verifizieren oder für zukünftige nicht verwandte Forschungen im Bereich der klinischen und kognitiven Neurowissenschaften. In diesen Ländern gelten die EU-Bestimmungen zum Schutz Ihrer persönlichen Daten nicht. Ihre Privatsphäre wird jedoch durch eine Vereinbarung über die gemeinsame Nutzung und Verwendung von Daten auf gleichem Niveau geschützt.
:::
::: {.content-visible when-profile="en"}
## 6) **Passing on to countries outside the European Union (EU)**

Your encoded data can also be accessed by and sent to countries outside the EU. This is necessary so that non-EU based scientists can run analyses to verify the scientific results produced from this study or for future unrelated research in the field of clinical and cognitive neuroscience. In those countries, the EU rules on the protection of your personal data do not apply. However, your privacy is protected by an agreement on the sharing and use of data with the same standard. 
:::


::: {.content-visible when-profile="de"}
## 7) **Weitere Informationen über Ihre Rechte bei der Datenverarbeitung** 

Für allgemeine Informationen über Ihre Rechte bei der Verarbeitung Ihrer persönlichen Daten können Sie die Website der Datenschutzbehörde konsultieren.

Wenn Sie Fragen zu Ihren Rechten haben, wenden Sie sich bitte an die für die Verarbeitung Ihrer persönlichen Daten zuständige Person. Das heißt, für diese Studie:
:::
::: {.content-visible when-profile="en"}
## 7) **More information about your rights regarding the processing of the data**

For general information about your rights regarding the processing of your personal data, you can consult the website of the data protection authority.

If you have questions about your rights, please contact the person responsible for the processing of your personal data. For this study, that is:
:::

- `{python} toml['Consentform']['data_processing_contactperson']`

::: {.content-visible when-profile="de"}
Wenn Sie Fragen oder Beschwerden über die Verarbeitung Ihrer persönlichen Daten haben, empfehlen wir Ihnen, sich zunächst an die Forschungsstelle zu wenden. Sie können sich auch an den Datenschutzbeauftragten der Universität Stuttgart oder an die Datenschutzbehörde von Baden-Württemberg wenden.  
\

Ort, Datum, Unterschrift: .........................................................................
:::
::: {.content-visible when-profile="en"}
If you have questions or complaints about the processing of your personal data, we advise you to first contact the research unit. You can also contact the Data Protection Officer of the University of Stuttgart or the Data Protection Authority of the Land Baden-Württemberg.
 
\
\
\

Place, Date, Signature: .........................................................................
:::
